version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - export BUCKET=theatrethrives-lambdas3bucket-1vwhggkgje5du
      - aws cloudformation package --template-file cloudformation.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - cloudformation.yml
    - outputtemplate.yml
